FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY media_service/ ./media_service

EXPOSE 2000

CMD ["uvicorn", "media_service.main:app","--host", "0.0.0.0", "--port", "2000"]