version: "3.9"

services:

  database:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: memes_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
     - "9000:9000"
     - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on: 
      - database

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on: 
      - database
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - MINIO_ENDPOINT_HOST=minio
      - MINIO_ENDPOINT_PORT=9000
  
  media:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.media
    depends_on: 
      - minio
    ports:
      - 2000:2000
    environment:
      - MINIO_ENDPOINT_HOST=minio
      - MINIO_ENDPOINT_PORT=9000
  

  
    
